# Generated by Django 4.2.6 on 2023-10-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
