# Generated by Django 4.2.3 on 2023-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=150)),
                ('image', models.CharField(default='testimage', max_length=150)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra-Large')], max_length=20)),
                ('weight', models.CharField(blank=True, choices=[('250g', '250 gram'), ('500g', '500 gram'), ('1kg', '1 Kilogram'), ('1.5kg', '1.5 Kilogram')], max_length=20)),
            ],
        ),
    ]
